sudo: required
services:
  - docker
before_install:
  - docker  build -t tarkesh2shar/test -f DockerFile.dev .
script:
  - docker run tarkesh2shar/test npm run test
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  bucket_name: "elasticbeanstalk-ap-south-1-887171905960"
  bucket_path: "docker"
  app: "reactSingleContainer"
  env: "Reactsinglecontainer-env"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret-access-key: $AWS_SECRET_KEY
